services:
  catalogdb:
    image: postgres:18
    restart: unless-stopped
    container_name: catalogdb
    networks:
      - eshop
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: CatalogDb
    volumes:
      - catalogdb:/var/lib/postgresql
  basketdb:
    image: postgres:18
    restart: unless-stopped
    container_name: basketdb
    networks:
      - eshop
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: BasketDb
    volumes:
      - basketdb:/var/lib/postgresql 
  redis:
    image: redis:latest
    restart: unless-stopped
    container_name: redis
    networks:
      - eshop
    ports:
      - 6379:6379
    volumes:
      - redis:/data
      #environment:
      #- REDIS_ARGS=--requirepass your_password_here --appendonly yes
  catalog.api:
    container_name: catalog.api
    depends_on:
      - catalogdb
    image: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=192.168.1.101;Port=5432;Database=CatalogDb;User Id=postgres;Password=postgres;Include Error Detail=true
    networks:
      - eshop
    ports:
      - 6000:8080
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
  
  basket.api:
    image: basket.api
    container_name: basket.api
    depends_on:
      - basketdb
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__Database=Server=192.168.1.101;Port=5433;Database=BasketDb;User Id=postgres;Password=postgres;Include Error Detail=true 
      - ConnectionStrings__Redis=192.168.1.101:6379
    ports:
      - 6001:8080 
    networks:
      - eshop
    build:
      context: .
      dockerfile: src/Services/Basket/Basket.API/Dockerfile    
networks:
  eshop:
    #external: true
    driver: bridge
volumes:
  catalogdb:
    external: true
  basketdb:
    external: true  
  redis:
    external: true  