services:
  catalog.api:
    container_name: catalog.api
    image: catalog.api
    networks:
      - eshop
    ports:
      - 5050:8081
    build:
      context: .
      dockerfile: src/Services/Catalog/Catalog.API/Dockerfile
  
  catalogdb:
    image: postgres:18
    container_name: postgres
    networks:
      - eshop
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: catalogdb  
    volumes:
      - postgres:/var/lib/postgresql
networks:
  eshop:
    #external: true
    driver: bridge
volumes:
  postgres:
    external: true      